# SPDX-FileCopyrightText: d-k-bo <d-k-bo@mailbox.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          branch: main
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
